apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/srgkinley/task-sql.git
    targetRevision: HEAD
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
