apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plain-yaml-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/srgkinley/task-sql.git
    targetRevision: HEAD
    path: root-app/app2/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

