apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - hpa-low.yaml

replacements:
  - source:
      kind: ConfigMap
      name: ms-config
      fieldPath: data.name
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - metadata.name
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
      - select:
          kind: HorizontalPodAutoscaler
        fieldPaths:
          - metadata.name
          - spec.scaleTargetRef.name

# patches:
#   - target:
#       group: autoscaling
#       version: v2
#       kind: HorizontalPodAutoscaler
#       name: ms-hpa-low
#     path: patch-deploy.yaml