apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - hpa-low.yaml

replacements:
  - source:
      kind: Deployment
      name: pgadmin
      fieldPath: metadata.name
    targets:
      - select:
          kind: HorizontalPodAutoscaler
        fieldPaths:
          - metadata.name
          - spec.scaleTargetRef.name

namePrefix: "dev-"