apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dev-mysql
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          exec:
            command:
            - mysqladmin
            - ping
            - -h127.0.0.1
            - -u
            - root
            - -p$(MYSQL_ROOT_PASSWORD)
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dev-postgres
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          exec:
            command:
            - pg_isready
            - -d
            - $POSTGRES_DB
            - -U
            - $POSTGRES_USER
            - -h
            - 127.0.0.1
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30