apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ingress-adminer.yaml
  - ingress-pgadmin.yaml

patches:
  - target:
      group: networking
      version: v1
      kind: Ingress
      name: adminer-ingress
    path: patch-ingress-adminer.yaml