apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - adminer.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: adminer
    patch: |
      - op: replace
        path: /spec/replicas
        value: 20