apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: pgadmin
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources/requests
        value:
          cpu: "100m"
          memory: "128Mi"
      
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: "200m"
          memory: "256Mi"