apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-pod
  template:
    metadata:
      labels:
        app: db-pod
    spec:
      containers:
      - name: db-pod-cont
        image: mongodb