apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adminer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080  
