apiVersion: v1
kind: PersistentVolume
metadata:
 name: backup-pv
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: manual
 hostPath:
  path: "/mnt/data/backup"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: backup-pvc
spec:
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
    storage: 1Gi
