apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/cron
  - ../../components/pvc
  - ../../components/ingress
  - ../../components/svc
  - ../../components/adminer
  - ../../components/resources/medium
  - ../../components/resources/high
  - ../../components/resources/critical

patches:
  - target: 
    kind: Deployment
    name: pgadmin
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5