apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

components:
  - ../../components/cron
  - ../../components/pvc
  - ../../components/ingress
  - ../../components/svc
  
patchesStrategicMerge:
- adminer.yaml 
- ingress-adminer-dev.yaml
- pgadmin-dev.yaml


