apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/cron
  - ../../components/pvc
  - ../../components/ingress
  - ../../components/svc
  - ../../components/adminer

patchesStrategicMerge:
- pgadmin-dev.yaml